# Generated by Django 5.2.1 on 2025-05-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loutre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('village', models.CharField(max_length=100)),
                ('poids', models.FloatField(help_text='Poids en kg')),
                ('taille', models.FloatField(help_text='Taille en cm')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('heure_lancement', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(help_text="Niveau dans l'arbre, ex : 3 pour quarts, 2 demi, 1 finale")),
                ('numero_match', models.IntegerField(help_text='Numéro du match dans le niveau')),
                ('heure_lancement', models.DateTimeField(blank=True, null=True)),
                ('loutre1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_loutre1', to='tournois.loutre')),
                ('loutre2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_loutre2', to='tournois.loutre')),
                ('vainqueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_gagnes', to='tournois.loutre')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='tournois.tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(help_text="Pseudo de l'utilisateur qui parie (temporaire)", max_length=100)),
                ('resultat', models.BooleanField(blank=True, help_text='True = gagné, False = perdu, Null = pas encore terminé', null=True)),
                ('loutre_misee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournois.loutre')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paris', to='tournois.match')),
            ],
        ),
    ]
